export const permissionList = [
  {
    resource_name: 'Menu',
    icon: '',
    path: '',
    id: 1,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Import data',
    icon: '',
    path: '/import-data',
    id: 2,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Parcel',
    icon: '',
    path: '/parcel',
    id: 3,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Bill',
    icon: '',
    path: '/bill',
    id: 4,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Payment',
    icon: '',
    path: '/payment',
    id: 5,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Income / Expenses',
    icon: '',
    path: '/income',
    id: 6,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Report',
    icon: '',
    path: '/report',
    id: 7,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Accounting',
    icon: '',
    path: '/accounting',
    id: 8,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Income / Expenses',
    icon: '',
    path: '/incomeExpenses',
    id: 9,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Return parcel',
    icon: '',
    path: '/returnParcel',
    id: 10,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Setting',
    icon: '',
    path: '/setting',
    id: 11,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Currency',
    icon: '',
    path: '/currency',
    id: 12,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Customer level',
    icon: '',
    path: '/customer-level',
    id: 13,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Customer',
    icon: '',
    path: '/customer',
    id: 14,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Role & permission',
    icon: '',
    path: '/role',
    id: 15,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'Department',
    icon: '',
    path: '/department',
    id: 16,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
  {
    resource_name: 'User',
    icon: '',
    path: '/user',
    id: 17,
    can_view: 0,
    can_update: 0,
    can_create: 0,
    can_delete: 0,
    can_export: 0,
  },
];
